# Generated by Django 5.1.6 on 2025-03-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('subtasks', models.SlugField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('UR', 'Urgent'), ('ME', 'Medium'), ('LO', 'Low')], max_length=50)),
                ('category', models.CharField(choices=[('Tec', 'Technical Task'), ('Use', 'User Story')], max_length=50)),
                ('assignees', models.ManyToManyField(related_name='Users', to='ticket.user')),
            ],
        ),
    ]
