# Generated by Django 5.1.6 on 2025-03-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assignees',
            field=models.ManyToManyField(related_name='assignees', to='ticket.user'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subtasks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
